import { db } from "./db";
import { serviceProviders, resources, jobListings } from "@shared/schema";

async function seedFeatures() {
  console.log("Seeding service providers, resources, and job listings...");

  // Seed Service Providers
  const providerCount = await db.select().from(serviceProviders);
  if (providerCount.length === 0) {
    await db.insert(serviceProviders).values([
      {
        name: "NDIS Quality and Safeguards Commission",
        category: "legal",
        description: "The government body that regulates NDIS providers and protects participants. File complaints, understand your rights, and access information about registered providers.",
        location: "National",
        state: "National",
        phone: "1800 035 544",
        website: "https://www.ndiscommission.gov.au",
        ndisRegistered: false,
        acceptsNdis: false,
        disabilityTypes: [],
        approved: true,
      },
      {
        name: "Scope Australia",
        category: "allied_health",
        description: "Provides a broad range of supports for people with disability including speech pathology, occupational therapy, physiotherapy, and early childhood intervention.",
        location: "Melbourne",
        state: "VIC",
        phone: "1300 4 72673",
        website: "https://www.scopeaust.org.au",
        ndisRegistered: true,
        acceptsNdis: true,
        disabilityTypes: ["physical", "intellectual", "communication"],
        approved: true,
      },
      {
        name: "Ability First Australia",
        category: "support_worker",
        description: "Support coordination and support workers helping people with disability live independently. NDIS registered, available across major metropolitan areas.",
        location: "Sydney",
        state: "NSW",
        phone: "1300 131 227",
        website: "https://www.abilityfirst.com.au",
        ndisRegistered: true,
        acceptsNdis: true,
        disabilityTypes: ["physical", "intellectual", "autism", "mental_health"],
        approved: true,
      },
      {
        name: "Summer Foundation",
        category: "accommodation",
        description: "Advocates for and supports young people with disability living in nursing homes to move into appropriate accommodation in the community.",
        location: "Melbourne",
        state: "VIC",
        phone: "03 9894 7006",
        website: "https://www.summerfoundation.org.au",
        ndisRegistered: false,
        acceptsNdis: false,
        disabilityTypes: ["physical", "acquired_brain_injury"],
        approved: true,
      },
      {
        name: "JobAccess",
        category: "employment",
        description: "Australian Government's free, confidential service providing information and advice to employers and people with disability on supported employment and workplace adjustments.",
        location: "National",
        state: "National",
        phone: "1800 464 800",
        website: "https://www.jobaccess.gov.au",
        ndisRegistered: false,
        acceptsNdis: false,
        disabilityTypes: [],
        approved: true,
      },
      {
        name: "Beyond Blue",
        category: "mental_health",
        description: "Works to reduce the impact of anxiety, depression, and suicide in Australia. Provides free information, resources, and a 24/7 support line for people with mental health conditions.",
        location: "National",
        state: "National",
        phone: "1300 22 4636",
        website: "https://www.beyondblue.org.au",
        ndisRegistered: false,
        acceptsNdis: false,
        disabilityTypes: ["mental_health", "anxiety", "depression"],
        approved: true,
      },
      {
        name: "Disability Services Australia",
        category: "support_worker",
        description: "One of Australia's largest disability service providers, offering residential support, day programs, community participation, and employment services across NSW.",
        location: "Parramatta",
        state: "NSW",
        phone: "02 9840 9400",
        website: "https://www.dsa.org.au",
        ndisRegistered: true,
        acceptsNdis: true,
        disabilityTypes: ["intellectual", "physical", "autism"],
        approved: true,
      },
      {
        name: "Blind Citizens Australia",
        category: "legal",
        description: "Consumer organisation of and for people who are blind or have low vision. Provides advocacy, peer support, and information about assistive technology and services.",
        location: "National",
        state: "National",
        phone: "1800 033 660",
        website: "https://www.bca.org.au",
        ndisRegistered: false,
        acceptsNdis: false,
        disabilityTypes: ["vision_impairment"],
        approved: true,
      },
      {
        name: "Assistive Technology Suppliers Australia",
        category: "equipment",
        description: "Industry association representing suppliers of assistive technology products including wheelchairs, communication devices, hearing aids, and home modifications.",
        location: "National",
        state: "National",
        website: "https://www.atsa.org.au",
        ndisRegistered: false,
        acceptsNdis: false,
        disabilityTypes: [],
        approved: true,
      },
      {
        name: "Relationships Australia",
        category: "mental_health",
        description: "Provides counselling, mediation, and support services for individuals, couples, and families. Experienced working with people with disability and their carers.",
        location: "National",
        state: "National",
        phone: "1300 364 277",
        website: "https://www.relationships.org.au",
        ndisRegistered: true,
        acceptsNdis: true,
        disabilityTypes: [],
        approved: true,
      },
    ]);
    console.log("✓ Service providers seeded");
  } else {
    console.log("✓ Service providers already exist, skipping");
  }

  // Seed Resources
  const resourceCount = await db.select().from(resources);
  if (resourceCount.length === 0) {
    await db.insert(resources).values([
      {
        title: "My NDIS Plan: Understanding Your Funding",
        description: "A comprehensive guide to understanding what's in your NDIS plan, how to use your funding categories, and what to do if you think something is wrong.",
        url: "https://www.ndis.gov.au/participants/your-plan",
        category: "ndis",
        tags: ["plan management", "funding", "supports"],
        source: "NDIS",
        isAustralian: true,
        approved: true,
        saves: 47,
      },
      {
        title: "Spoon Theory Explained",
        description: "The original essay by Christine Miserandino explaining spoon theory — a metaphor for the limited energy available to people living with chronic illness or disability.",
        url: "https://butyoudontlooksick.com/articles/written-by-christine/the-spoon-theory/",
        category: "community",
        tags: ["chronic illness", "energy management", "wellbeing"],
        source: "But You Don't Look Sick",
        isAustralian: false,
        approved: true,
        saves: 89,
      },
      {
        title: "Know Your Rights: Disability Discrimination",
        description: "The Australian Human Rights Commission's guide to the Disability Discrimination Act — what counts as discrimination, how to make a complaint, and your legal protections.",
        url: "https://humanrights.gov.au/our-work/disability-rights/guides-and-toolkits",
        category: "legal",
        tags: ["discrimination", "rights", "DDA", "advocacy"],
        source: "Australian Human Rights Commission",
        isAustralian: true,
        approved: true,
        saves: 34,
      },
      {
        title: "Accessing Mental Health Support with NDIS",
        description: "A practical guide to accessing psychosocial supports through the NDIS, including what supports are available, how to get them, and how they interact with Medicare.",
        url: "https://www.ndis.gov.au/participants/working-providers/psychosocial-disability",
        category: "mental_health",
        tags: ["psychosocial", "mental health", "support coordination"],
        source: "NDIS",
        isAustralian: true,
        approved: true,
        saves: 28,
      },
      {
        title: "Employment Assistance Fund (EAF)",
        description: "Government funding available to help employers make adjustments for employees and job seekers with disability. Learn what you can get reimbursed for.",
        url: "https://www.jobaccess.gov.au/employment-assistance-fund",
        category: "employment",
        tags: ["workplace adjustments", "funding", "employer"],
        source: "JobAccess",
        isAustralian: true,
        approved: true,
        saves: 21,
      },
      {
        title: "Housing Options for People with Disability",
        description: "A guide to the different housing options funded by the NDIS, including Supported Independent Living (SIL), Specialist Disability Accommodation (SDA), and home modifications.",
        url: "https://www.ndis.gov.au/participants/home-and-living",
        category: "housing",
        tags: ["SDA", "SIL", "accommodation", "housing"],
        source: "NDIS",
        isAustralian: true,
        approved: true,
        saves: 55,
      },
      {
        title: "Headspace: Mental Health for Young People",
        description: "National youth mental health foundation providing early intervention mental health services to Australians aged 12-25 with both in-person and online support.",
        url: "https://www.headspace.org.au",
        category: "mental_health",
        tags: ["youth", "mental health", "counselling", "online"],
        source: "Headspace",
        isAustralian: true,
        approved: true,
        saves: 43,
      },
      {
        title: "Assistive Technology for Accessibility",
        description: "Explore assistive technology tools including screen readers, communication devices, AAC apps, and other tools to support independence and communication.",
        url: "https://www.atsa.org.au/resources",
        category: "tools",
        tags: ["AAC", "screen readers", "AT", "independence"],
        source: "ATSA",
        isAustralian: true,
        approved: true,
        saves: 38,
      },
      {
        title: "Disability Research Digest",
        description: "Monthly digest of disability research from Australia's universities and research institutions, translated into plain English for community members.",
        url: "https://www.nds.org.au/resources",
        category: "research",
        tags: ["research", "evidence", "policy"],
        source: "National Disability Services",
        isAustralian: true,
        approved: true,
        saves: 16,
      },
      {
        title: "Centrelink Disability Support Pension Guide",
        description: "Step-by-step guide to applying for the Disability Support Pension (DSP), including eligibility criteria, required medical evidence, and what to expect.",
        url: "https://www.servicesaustralia.gov.au/disability-support-pension",
        category: "ndis",
        tags: ["DSP", "income support", "Centrelink"],
        source: "Services Australia",
        isAustralian: true,
        approved: true,
        saves: 72,
      },
    ]);
    console.log("✓ Resources seeded");
  } else {
    console.log("✓ Resources already exist, skipping");
  }

  // Seed Job Listings
  const jobCount = await db.select().from(jobListings);
  if (jobCount.length === 0) {
    await db.insert(jobListings).values([
      {
        title: "Support Worker",
        company: "Scope Australia",
        description: "Join our team supporting adults with disability to live independently in the community. Shifts available across Melbourne's inner suburbs. Experience preferred but not essential — we provide full training.\n\nResponsibilities include personal care, community access, life skills support, and transport.",
        location: "Melbourne",
        state: "VIC",
        type: "part_time",
        salary: "$28–$35/hr + penalty rates",
        category: "healthcare",
        tags: ["disability support", "community care"],
        isRemote: false,
        isAccessible: true,
        disabilityWelcome: true,
        applyUrl: "https://www.scopeaust.org.au/careers",
        approved: true,
      },
      {
        title: "Data Entry Officer (Remote)",
        company: "Ability Connect",
        description: "We're looking for an organised and detail-oriented Data Entry Officer to work fully remotely. Flexible hours — work when you're at your best. Perfect for people with disability who thrive in a structured, low-sensory environment.\n\nFull equipment provided. Adjustments available for all candidates.",
        location: "Any city",
        state: "National",
        type: "part_time",
        salary: "$55,000–$60,000 pro-rata",
        category: "admin",
        tags: ["remote", "flexible hours", "data entry"],
        isRemote: true,
        isAccessible: true,
        disabilityWelcome: true,
        applyEmail: "careers@abilityconnect.com.au",
        approved: true,
      },
      {
        title: "Web Accessibility Consultant",
        company: "InclusiveDigital",
        description: "Help organisations make their digital products accessible. You'll conduct WCAG audits, produce reports, and advise development teams.\n\nWe welcome applications from people with disability — lived experience of accessibility barriers is genuinely valued here.",
        location: "Sydney",
        state: "NSW",
        type: "contract",
        salary: "$80–$120/hr",
        category: "tech",
        tags: ["WCAG", "accessibility", "consulting", "remote friendly"],
        isRemote: true,
        isAccessible: true,
        disabilityWelcome: true,
        applyUrl: "https://inclusivedigital.com.au/jobs",
        approved: true,
      },
      {
        title: "Community Events Volunteer",
        company: "Disability Advocacy Network Australia",
        description: "Help run community events for people with disability including peer support groups, social outings, and awareness campaigns. This is a volunteer role with out-of-pocket expenses reimbursed.\n\nAll ability levels welcome. Tasks can be adjusted to your needs.",
        location: "Brisbane",
        state: "QLD",
        type: "volunteer",
        category: "community",
        tags: ["volunteering", "community", "events"],
        isRemote: false,
        isAccessible: true,
        disabilityWelcome: true,
        applyEmail: "volunteer@dana.org.au",
        approved: true,
      },
      {
        title: "Disability Employment Consultant",
        company: "APM Employment Services",
        description: "Work with job seekers who have disability, injury or health conditions to help them find and keep meaningful employment. You'll build relationships with local employers and provide ongoing support.\n\nExperience in disability, social work or HR preferred.",
        location: "Perth",
        state: "WA",
        type: "full_time",
        salary: "$65,000–$75,000",
        category: "admin",
        tags: ["employment services", "disability", "case management"],
        isRemote: false,
        isAccessible: true,
        disabilityWelcome: true,
        applyUrl: "https://www.apm.net.au/careers",
        approved: true,
      },
      {
        title: "Graphic Designer (Flexible Hours)",
        company: "Creative Access Australia",
        description: "We're a design agency focused on inclusive communications. Looking for a graphic designer with portfolio experience in print and digital.\n\nCompletely flexible hours and work-from-home. Regular check-ins via video call. Adjustments available — just ask.",
        location: "Adelaide",
        state: "SA",
        type: "casual",
        salary: "$35–$50/hr",
        category: "creative",
        tags: ["design", "remote", "flexible", "creative"],
        isRemote: true,
        isAccessible: true,
        disabilityWelcome: true,
        applyEmail: "hello@creativeaccess.com.au",
        approved: true,
      },
    ]);
    console.log("✓ Job listings seeded");
  } else {
    console.log("✓ Job listings already exist, skipping");
  }

  console.log("✓ All feature data seeded successfully!");
  process.exit(0);
}

seedFeatures().catch(err => {
  console.error("Seed error:", err);
  process.exit(1);
});
